version: '3.7'
services:
  mongodb:
    volumes:
      - ../volumes/mongodb/data:/data/db # 指定容器外部的数据存储位置
    ports:
      - '27017:27017'
    # logging:
    # driver: 'none'

  back:
    ports:
      - '3000:3000'
    environment:
      # - TMS_KOA_PORT=3000
      - TMS_FINDER_MONGODB_HOST=mongodb
      - TMS_FINDER_MONGODB_PORT=27017
      - TMS_FINDER_FS_ROOTDIR=/home/storage
    volumes:
      - ../volumes/files:/home/storage # 指定文件服务的外部存储位置（rootDir）

  ue:
    build:
      args:
        vue_app_auth_server: https://localhost:3000
        vue_app_api_server: https://localhost:3000
        vue_app_fs_server: https://localhost:3000
    ports:
      - '8443:443'

  ue_any:
    build:
      args:
        vue_app_auth_server: https://localhost:3000
        vue_app_api_server: https://localhost:3000
        vue_app_upload_lib_url: https://localhost:8080/finder_ue/lib
    ports:
      - '8444:443'
